version: "3"

networks:
  moitoring:
    driver: bridge

volumes:
  grafana-vol:
    external: true

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose:
      - 9100
    networks:
      - moitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    expose:
      - 9090
    networks:
      - moitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-vol:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - moitoring
  apache:
    image: ubuntu/apache2
    container_name: apache
    ports:
      - 8080:80
    networks:
      - moitoring
    volumes:
      - ./apache/status.conf:/etc/apache2/mods-enabled/status.conf
  apache-exporter:
    image: bitnami/apache-exporter
    container_name: apache-exporter
    ports:
      - 9117:9117
    networks:
      - moitoring
    depends_on:
      - apache
    command:
      - --scrape_uri=http://apache:80/server-status?auto
